spring:
  application:
    name: hanteo
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: public
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      username: sa
      password:
