CREATE TABLE board
(
    board_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255) comment '게시판 명',
    CONSTRAINT pk_board PRIMARY KEY (board_id)
);

CREATE TABLE category
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255) comment '카테고리 명',
    CONSTRAINT pk_category PRIMARY KEY (category_id)
);

CREATE TABLE category_boards
(
    board_id    BIGINT NOT NULL,
    category_id BIGINT NOT NULL
);

CREATE TABLE category_relation
(
    child_id   BIGINT NOT NULL,
    parent_idx BIGINT NOT NULL,
    CONSTRAINT pk_category_relation PRIMARY KEY (child_id, parent_idx)
);

ALTER TABLE category
    ADD CONSTRAINT uc_category_name UNIQUE (name);

ALTER TABLE category_boards
    ADD CONSTRAINT fk_catboa_on_board FOREIGN KEY (board_id) REFERENCES board (board_id);

ALTER TABLE category_boards
    ADD CONSTRAINT fk_catboa_on_category FOREIGN KEY (category_id) REFERENCES category (category_id);

ALTER TABLE category_relation
    ADD CONSTRAINT fk_catrel_on_child FOREIGN KEY (child_id) REFERENCES category (category_id);

ALTER TABLE category_relation
    ADD CONSTRAINT fk_catrel_on_parent_idx FOREIGN KEY (parent_idx) REFERENCES category (category_id);
